/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Enzo
 */
public class Principal extends javax.swing.JFrame {

    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btnproductos;
    private javax.swing.JButton btnventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelprincipal1;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("Ventana Principal");
        setSize(450,350);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnproductos = new javax.swing.JButton();
        btnclientes = new javax.swing.JButton();
        btnventas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //getContentPane().setLayout(null);

        panelprincipal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelprincipal1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CERRAR SESIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelprincipal1.add(jButton1);
        jButton1.setBounds(10, 249, 140, 40);

        btnproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnproductos.setText("PRODUCTOS");
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        panelprincipal1.add(btnproductos);
        btnproductos.setBounds(10, 12, 130, 43);

        btnclientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnclientes.setText("CLIENTES");
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });
        panelprincipal1.add(btnclientes);
        btnclientes.setBounds(143, 12, 130, 43);

        btnventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnventas.setText("VENTAS");
        btnventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasActionPerformed(evt);
            }
        });
        panelprincipal1.add(btnventas);
        btnventas.setBounds(283, 11, 130, 46);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO AL SISTEMA");
        panelprincipal1.add(jLabel1);
        jLabel1.setBounds(10, 90, 240, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("REGISTRAR");
        panelprincipal1.add(jButton2);
        jButton2.setBounds(10, 160, 110, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("CONSULTAR");
        panelprincipal1.add(jButton3);
        jButton3.setBounds(140, 160, 120, 40);

        getContentPane().add(panelprincipal1);
        panelprincipal1.setBounds(0, 0, 450, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        Productos pro= new Productos();
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnproductosActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        Clientes cli= new Clientes();
        cli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
        /*Ventas vent = new Ventas();
        vent.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_btnventasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login logn= new Login();
        logn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Principal miVentana= new Principal();
        VentanaLogin miLogin= new VentanaLogin(miVentana, true);
        miLogin.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
}
